export default [
  {
    id: "abcd1004",
    name: "Original_Cola",
    price: 1000,
    quantity: 10,
    source: "./img/beverageImg/Original_Cola.png",
    alt: "오리지널 콜라",
  },
  {
    id: "bcds3294",
    name: "Violet_Cola",
    price: 1000,
    quantity: 0,
    source: "./img/beverageImg/Violet_Cola.png",
    alt: "보라색 콜라",
  },
  {
    id: "sfei9013",
    name: "Yellow_Cola",
    price: 1500,
    quantity: 10,
    source: "./img/beverageImg/Yellow_Cola.png",
    alt: "노란색 콜라",
  },
  {
    id: "hdok3920",
    name: "Cool_Cola",
    price: 2000,
    quantity: 10,
    source: "./img/beverageImg/Cool_Cola.png",
    alt: "하늘색 콜라",
  },
  {
    id: "npiq9284",
    name: "Green_Cola",
    price: 1500,
    quantity: 10,
    source: "./img/beverageImg/Green_Cola.png",
    alt: "초록색 콜라",
  },
  {
    id: "zmit5821",
    name: "Orange_Cola",
    price: 1000,
    quantity: 10,
    source: "./img/beverageImg/Orange_Cola.png",
    alt: "주황색 콜라",
  },
];
