export default [
  {
    id: "abcd1004",
    name: "Original_Cola",
    price: 1000,
    quantity: 10,
    source: "./src/img/beverageImg/Original_Cola.png",
  },
  {
    id: "bcds3294",
    name: "Violet_Cola",
    price: 1000,
    quantity: 0,
    source: "./src/img/beverageImg/Violet_Cola.png",
  },
  {
    id: "sfei9013",
    name: "Yellow_Cola",
    price: 1500,
    quantity: 10,
    source: "./src/img/beverageImg/Yellow_Cola.png",
  },
  {
    id: "hdok3920",
    name: "Cool_Cola",
    price: 2000,
    quantity: 10,
    source: "./src/img/beverageImg/Cool_Cola.png",
  },
  {
    id: "npiq9284",
    name: "Green_Cola",
    price: 1500,
    quantity: 10,
    source: "./src/img/beverageImg/Green_Cola.png",
  },
  {
    id: "zmit5821",
    name: "Orange_Cola",
    price: 1000,
    quantity: 10,
    source: "./src/img/beverageImg/Orange_Cola.png",
  },
  {
    id: "ssvw8433",
    name: "Yellow_Cola2",
    price: 1500,
    quantity: 0,
    source: "./src/img/beverageImg/Yellow_Cola.png",
  },
  {
    id: "kwsdk0435",
    name: "Cool_Cola2",
    price: 3000,
    quantity: 10,
    source: "./src/img/beverageImg/Cool_Cola.png",
  },
  {
    id: "9kjd3l9j",
    name: "Violet_Cola2",
    price: 4000,
    quantity: 10,
    source: "./src/img/beverageImg/Violet_Cola.png",
  },
  {
    id: "l0j2m0",
    name: "Original_Cola2",
    price: 5000,
    quantity: 10,
    source: "./src/img/beverageImg/Original_Cola.png",
  },
];
